language: node_js
node_js:
- node
before_install:
- npm install -g greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
script:
- npm run build
after_script:
- greenkeeper-lockfile-upload
after_success:
- npm run-script coveralls
- ./.ci/update-gh-pages.sh
cache:
  directories:
  - node_modules
env:
  global:
    - secure: 0KhGiEEwX3VFDn0v4Crlf+TIy1dyfuKMxM9wdArrV1Z49m3640C1VQkN19/wSruHHXDCfPV+BOfciiGvXuNqQt41Ssd0VUdRvu7jhh9DRWxNiXRagCnnEfF0sGndekQCWNAm3+8az1HbgXTDoV9lgxP2TIrx4lin1fV9VFvvaEE8IZcHDNM/Bi/QDRiQzErxxiIxZ7WuIB+L1l7DZ/pb0FVYb+s38O6Y4byapvY8/iUOsvrKzx1aepn7RLisr24LqHHxswrJDo810K05trt9XvVN+BaxJ8miKmcbBuhL8Egr8FKsJzH8iaIG1sanMyyurKnalEPzQOFYCKl2ydLvh3O8CcOq/LVdSMZtJShReeYMtPTUdKB+kWAuY0JUfcjVMeKM8Bkvpe+C61HRWBZoc1z71ItBDROaGvCygi57YBkZNEjPI+JkX9Wzc+Fdvjh4v3FZpnze5ndPr/mpvXLYZGo8luw9o3Mra2DIg7yVL0aYFIkmWSP3JOP4T44hHCswDRzZjFiJ7TiPwNwT3GzC2ti7tZYcaJ2xiiW3f1NXpgr1wNLmc1mIuFhDVDayEJO+QvU7m4IRWB36EmD5K83cbf4nxHUzhw3qd/R5Hq+Nez9Ybk5BT2q5aouAtHuKpZf8QlYq+2u/xs9sZkaZvHJ+14hrCLSRbSkRiv7yqWSgbjo=
    - secure: "cyTGV2o6Tio2SaXTW4PKDLBD/fLmP9RR9oJuwAH0s6cIGKXkdzlroyiqQsKxII5Un7Rhw7Y7ayQGe0cLH0sDEXzIkWF4BhSvWJJTHv2DM7DbDKbfPwXJ/UgCN298emGPXxixWpI1t1vjzZeVosOVDIisONg9GdMcl42wrTL0dyuSDI2GfLuE3DD/Ktm0eQpHLbJJS7peWGH8JOClOKOBb2yY7aqYbb9vgXRaiGafuJed+yqtOUbgkV4D1Jtas8tZCllej76rZobZT33oWsQvoYqLz8afQBkmhVEcwJDfiFhxiS38hA/yqSXXiUCzU8KJHT1ibGqfmMduBFkZ7f4vjXpSEENh0tn0JkX5ZuZcT7TunpogrkQfeHKjkq4Kc4rb+pIM9mAmNjbnj+l5gkJsm+vjFse/vaGapMz9CabFFUHvkAl3pXLoAKUOj1d8oTVPpUCJs57G1gEcoioi+d2Xx7QpvjldbVRISVAb1a3Frrb1rEDcB/Zh06f3aagoR/GXQyg/jeehDp+ViFoa9xUq3up7yvNvHnb4oOdmv6y3v2bs12AsdaG2dSNHN9v8sOQmcJPM1250b5kkoypXxD+eKpCRqhhQ7KzxNPzKkQh25qvBVQqXfCNQ33gXPGtsnZsxwkKbRFl61e0c0fRN6LFt7mXvqOLTA8M2+NvCUwdpBBo="
