name: 💡 Feature request
description: Suggest an idea for the project
title: "[Feature]: "
labels: ["feature"]
assignees:
  - ahennr
  - annarieger
  - dnlkoch
  - weskamm
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your suggestion! 💞
  - type: textarea
    attributes:
      label: Related issue
      description: Is there an issue related to the feature request?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Feature request
      description: Describe the solution you'd like.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the idea you have!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terrestris/react-geo/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
