name: ❓ Question
description: Ask a question related to the project
title: "[Question]: "
labels: ["question"]
assignees:
  - ahennr
  - annarieger
  - dnlkoch
  - weskamm
body:
  - type: textarea
    attributes:
      label: Your question
      description: Propose your question here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the question you have!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terrestris/react-geo/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
